Fixed long compilation issue and made code a bit more idiomatic
avr-rust/avrd pull request #16
Opened 2020-05-01 05:39 UTC by Logarithmus

Due to the bug in https://github.com/avr-rust/avr-mcu (CARGO_CFG_TARGET_CPU environment variable actually is not being set by avr-rust compiler), and also because `cfg!(arch = "avr")` doesn't work for unknown reason, build.rs always generates files for ALL microcontrollers, even if you specify one in custom target *.json file via `"cpu": "atmega88pa"` line, like in `blink` example.

So I decided to take a look at the code. Now `avr-mcu` uses `TARGET` environment variable to get the name of *.json file. It should be the same as -mmcu flag passed to `avr-gcc`. I understand that this change breaks `blink` example and other projects, so I bumped minor version number instead of patch.

PR for avr-mcu:

2020-05-02 05:05 UTC, dylanmckay requested changes
I will look at this more once the version is updated in `Cargo.toml`

2020-05-02 05:05 UTC, dylanmckay commented on Cargo.toml
> +avr-mcu = { git = "https://github.com/Logarithmus/avr-mcu", branch = "master" }
Update to 0.3

2020-05-02 07:32 UTC, Logarithmus commented on Cargo.toml
> +avr-mcu = { git = "https://github.com/Logarithmus/avr-mcu", branch = "master" }
I fixed it

2020-05-08 21:31 UTC, Logarithmus commented
@dylanmckay , I'm waiting for the merge, possibly, you are busy to do it now?

2020-05-14 07:03 UTC, dylanmckay approved these changes

2020-05-14 07:05 UTC, dylanmckay commented
This patch is really good, I'm happy to see the dependence on the AVR-specific rustc flag removed!

Thanks @Logarithmus

2020-05-14 07:07 UTC, merged